services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: olist_project
      POSTGRES_USER: roses
      POSTGRES_PASSWORD: roses
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U roses -d olist_project"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
  minio_data:
